package com.der.miutisourceb.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Namespace implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.AppId
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.ClusterName
     *
     * @mbggenerated
     */
    private String clustername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.NamespaceName
     *
     * @mbggenerated
     */
    private String namespacename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.IsDeleted
     *
     * @mbggenerated
     */
    private Boolean isdeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.DataChange_CreatedBy
     *
     * @mbggenerated
     */
    private String datachangeCreatedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.DataChange_CreatedTime
     *
     * @mbggenerated
     */
    private Date datachangeCreatedtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.DataChange_LastModifiedBy
     *
     * @mbggenerated
     */
    private String datachangeLastmodifiedby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column namespace.DataChange_LastTime
     *
     * @mbggenerated
     */
    private Date datachangeLasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table namespace
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}