package com.der.mutisourcea.master.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Getter;
import lombok.Setter;

/**
 * Table: appnamespace
 */
@Getter
@Setter
public class Appnamespace implements Serializable {
    /**
     * 自增主键
     *
     * Table:     appnamespace
     * Column:    Id
     * Nullable:  false
     */
    private Integer id;

    /**
     * namespace名字，注意，需要全局唯一
     *
     * Table:     appnamespace
     * Column:    Name
     * Nullable:  false
     */
    private String name;

    /**
     * app id
     *
     * Table:     appnamespace
     * Column:    AppId
     * Nullable:  false
     */
    private String appid;

    /**
     * namespace的format类型
     *
     * Table:     appnamespace
     * Column:    Format
     * Nullable:  false
     */
    private String format;

    /**
     * namespace是否为公共
     *
     * Table:     appnamespace
     * Column:    IsPublic
     * Nullable:  false
     */
    private Boolean ispublic;

    /**
     * 注释
     *
     * Table:     appnamespace
     * Column:    Comment
     * Nullable:  false
     */
    private String comment;

    /**
     * 1: deleted, 0: normal
     *
     * Table:     appnamespace
     * Column:    IsDeleted
     * Nullable:  false
     */
    private Boolean isdeleted;

    /**
     * 创建人邮箱前缀
     *
     * Table:     appnamespace
     * Column:    DataChange_CreatedBy
     * Nullable:  false
     */
    private String datachangeCreatedby;

    /**
     * 创建时间
     *
     * Table:     appnamespace
     * Column:    DataChange_CreatedTime
     * Nullable:  false
     */
    private Date datachangeCreatedtime;

    /**
     * 最后修改人邮箱前缀
     *
     * Table:     appnamespace
     * Column:    DataChange_LastModifiedBy
     * Nullable:  true
     */
    private String datachangeLastmodifiedby;

    /**
     * 最后修改时间
     *
     * Table:     appnamespace
     * Column:    DataChange_LastTime
     * Nullable:  true
     */
    private Date datachangeLasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table appnamespace
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}