package com.der.mutisourcea.second.entity;

import java.io.Serializable;
import java.util.Date;
import lombok.Getter;
import lombok.Setter;

/**
 * Table: namespace
 */
@Getter
@Setter
public class Namespace implements Serializable {
    /**
     * 自增主键
     *
     * Table:     namespace
     * Column:    Id
     * Nullable:  false
     */
    private Integer id;

    /**
     * AppID
     *
     * Table:     namespace
     * Column:    AppId
     * Nullable:  false
     */
    private String appid;

    /**
     * Cluster Name
     *
     * Table:     namespace
     * Column:    ClusterName
     * Nullable:  false
     */
    private String clustername;

    /**
     * Namespace Name
     *
     * Table:     namespace
     * Column:    NamespaceName
     * Nullable:  false
     */
    private String namespacename;

    /**
     * 1: deleted, 0: normal
     *
     * Table:     namespace
     * Column:    IsDeleted
     * Nullable:  false
     */
    private Boolean isdeleted;

    /**
     * 创建人邮箱前缀
     *
     * Table:     namespace
     * Column:    DataChange_CreatedBy
     * Nullable:  false
     */
    private String datachangeCreatedby;

    /**
     * 创建时间
     *
     * Table:     namespace
     * Column:    DataChange_CreatedTime
     * Nullable:  false
     */
    private Date datachangeCreatedtime;

    /**
     * 最后修改人邮箱前缀
     *
     * Table:     namespace
     * Column:    DataChange_LastModifiedBy
     * Nullable:  true
     */
    private String datachangeLastmodifiedby;

    /**
     * 最后修改时间
     *
     * Table:     namespace
     * Column:    DataChange_LastTime
     * Nullable:  true
     */
    private Date datachangeLasttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table namespace
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;
}