package com.der.mutisourcea.master.dao;

import com.der.mutisourcea.master.entity.Appnamespace;

public interface AppnamespaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appnamespace
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appnamespace
     *
     * @mbggenerated
     */
    int insert(Appnamespace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appnamespace
     *
     * @mbggenerated
     */
    int insertSelective(Appnamespace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appnamespace
     *
     * @mbggenerated
     */
    Appnamespace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appnamespace
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Appnamespace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appnamespace
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Appnamespace record);
}