package com.der.miutisourceb.dao;

import com.der.miutisourceb.entity.Namespace;

import java.util.List;

public interface NamespaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table namespace
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table namespace
     *
     * @mbggenerated
     */
    int insert(Namespace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table namespace
     *
     * @mbggenerated
     */
    int insertSelective(Namespace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table namespace
     *
     * @mbggenerated
     */
    Namespace selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table namespace
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Namespace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table namespace
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Namespace record);

    List<Namespace> selectAll();
}